### ISSUE TITLE
SACNR API updated

### ISSUE THREAD

**Issue by dylannz** [spmn/sa-mp_masterlist_fix#3]
Hello

I have added the following endpoints to the SACNR API:

http://monitor.sacnr.com/list/masterlist.txt
http://monitor.sacnr.com/list/hostedlist.txt

These responses are cached for 15 mins so should be faster + a lot easier than parsing the HTML output from server lists. Please update to use these endpoints ASAP to avoid mass spamming of SACNR Monitor.

Cheers

**Comment by spmn** [comment]
Thank you for supporting this small project!

I've updated both source and binaries to query SACNR directly instead of other mirrors.
If you have time, please look into these two suggestions:
- IPs order should be randomized everytime they are cached instead of being determined by the number of players. This way new servers can have a chance against already established servers.
- eliminate non-0.3.7 servers. After a quick peek over masterlist, I've seen quite a lot of 0.3e and 0.3z servers.

Also, you can disable caching of hosted servers' IP because this project doesn't and won't ever interfere in any way with hosted list.

**Comment by dylannz** [comment]
I have randomised the IP order and now it should only serve 0.3.7\* servers.

Have left hosted tab list online for now - maybe someone will find it useful some day.

**Comment by spmn** [comment]
Everything is perfect now!
